language: python
python:
  - "2.7"
env:
  - DJANGO=1.8.2
install:
  - pip install coverage --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors -I
  - pip install coveralls
script:
  - coverage run --source='phonebook' manage.py test phonebook
  - coverage report -m
after_success:
  - coveralls
